package com.example.app.DTOs;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * This class represents the pdf report that is generated by the system
 */

@Data
public class ReportDTO {

    private byte[] info;
    private LocalDateTime date;
    private String fileName;
}
